name: Build, Compare Image Sizes and Comment

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        id: build
        run: |
          docker build -t ${{ env.CUSTOM_IMAGE_NAME }} .
          docker save ${{ env.CUSTOM_IMAGE_NAME }} > image.tar

      - name: Upload Docker image
        uses: actions/upload-artifact@v2
        with:
          name: image
          path: image.tar

  compare_image_sizes:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y jq skopeo

      - name: Download built image
        uses: actions/download-artifact@v2
        with:
          name: image

      - name: Get size of the built image
        id: built_image_size
        run: |
          BUILT_IMAGE_SIZE=$(stat -c%s image.tar)
          echo "BUILT_IMAGE_SIZE=$BUILT_IMAGE_SIZE" >> "$GITHUB_ENV"

      - name: Get size of the base image
        id: base_image_size
        run: |
          BASE_IMAGE_SIZE=$(skopeo inspect docker://ghcr.io/vanilla-os/nvidia:main | jq '.Size')
          echo "BASE_IMAGE_SIZE=$BASE_IMAGE_SIZE" >> "$GITHUB_ENV"

      - name: Compare image sizes
        run: |
          DIFFERENCE=$(expr $BUILT_IMAGE_SIZE - $BASE_IMAGE_SIZE)
          echo "DIFFERENCE=$DIFFERENCE" >> "$GITHUB_ENV"

      - name: Comment on PR
        uses: actions/github-script@v5
        with:
          script: |
            const issue_number = context.issue.number;
            const message = `The size of the built image is ${process.env.BUILT_IMAGE_SIZE} bytes, the size of the base image is ${process.env.BASE_IMAGE_SIZE} bytes, the difference is ${process.env.DIFFERENCE} bytes.`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: message
            });
